"
A TabularCellTest is a test class for testing the behavior of TabularCell
"
Class {
	#name : #TabularCellTest,
	#superclass : #TestCase,
	#category : #'Tabular-Tests'
}

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testColspan [

  "to implement"
   self deny: 1 = 1
]

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testRowspan [

 "to implement"
   self deny: 1 = 1
]

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testStyle [

   "to implement"
   self deny: 1 = 1
]

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testType [

 "to implement"
   self deny: 1 = 1
]
