"
I am TabularHTMLExport1 and export a worksheet to an XHTML file.


For the Responsibility part: Three sentences about my main responsibility, what I'm doing, what services do I offer.

For the Collaborators Part: State my main collaborators and one line about how I interact with them. 

Public API and Key Messages

- message one   
- message two 
- what is the way to create instances is a plus.

   One simple example is simply gorgeous.
 
Internal Representation and Key Implementation Points.


    Implementation Points
"
Class {
	#name : #TabularXHTMLExport1,
	#superclass : #TabularExport,
	#category : #'Tabular-Exporters'
}
