"
A TabularCellTest is a test class for testing the behavior of TabularCell
"
Class {
	#name : #TabularCellTest,
	#superclass : #TestCase,
	#category : #'Tabular-Tests'
}

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testColspan [
	<expectedFailure>
	self fail
]

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testRowspan [
	<expectedFailure>
	self fail
]

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testStyle [
	<expectedFailure>
	self fail
]

{ #category : #'tests-accessing - attributes' }
TabularCellTest >> testType [
	<expectedFailure>
	self fail
]
